services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mlops_labs
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mlops_labs"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 3s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    networks:
      - mlopslabs_network
    restart: unless-stopped

  app:
    image: ${APP_IMAGE:-mlops-labs:local}
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-}
        VCS_REF: ${VCS_REF:-local}
    container_name: mlops_labs_app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/healthz').read()\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M
    #no .env file yet, so we set environment variables directly in the docker-compose.yaml
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/mlops_labs"
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    networks:
      - mlopslabs_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  mlopslabs_network:
    driver: bridge
